### ISSUE TITLE
Project review

### ISSUE THREAD

**Issue by margauxgo** [ds4owd-001/project-efvicario#6]
@efvicario Congrats again on accomplishing your capstone project! We are happy that you went through the course with us and applied the skills in the project. Please excuse us for the late review, and note that it does not have any assessment on the writing content of the report.

Let us now have a look at your project. You completed all items in the [Required Items](https://ds4owd-001.github.io/website/project/#required-items). Awesome! Some items that can be improved are:

1. In a matter of reproducibility, it is encouraged to include the package installation code `install.packages()` at the beginning of your Quarto document. It is moreover recommended to separate it from the actual package importing `library()`, and to set different options for these two code chunks. For example, set `eval=FALSE` for the package installation code.
2. Your report only contains 4 chapters and the website link is not displayed in the **About** section of GitHub. Moreover, your repository is still private; does this have to do with you not wanting to share the data?
3. Your **dictionary.csv** file has 5 empty columns and some variables could have been put together; for example, the variables dw_reason_convenience, dw_reason_affordable, dw_reason_available, dw_reason_cold, dw_reason_clean, dw_reason_taste, dw_reason_habit, dw_reason_trustworthy, dw_reason_health, dw_reason_other could be grouped into one named dw_reason with character entries such as convenience, affordable, available, etc. This would make your data more understandable at first glance.

However, all these comments are minor suggestions: your report is well-written, concise and enjoyable to read! Great job! Moreover, given the fact that you collected the data yourself, we would love to have your project and data turning into an openwashdata data package! That means, we would develop an R data package that you would be an author. We could also add the data you mentioned that concerns information about primary drinking water sources and reasoning which was collected but not analyzed here. You and others could directly use a tidy version of the data in R later. Please let us know if you are interested in this! @mianzg @larnsce

**Comment by efvicario** [comment]
Hi! Thank you for the feedback!

I just made some changes, including making the repository public and incorporating those edits into my dictionary. I would add the link to the "About" section but I'm not sure where to link to.... https://github.com/ds4owd-001/project-efvicario? Isn't that the page that the viewer is already on?

That would be great, I also collected data through other questions that I didn't include. I likely won't be using it for my current project so would love to publish it for others to use.

Elizabeth

**Comment by margauxgo** [comment]
@efvicario Concerning the link to add to the **About** section, you can follow these steps (we use GitHub Pages):

<img width="1365" alt="Screenshot 2024-04-23 at 16 06 18" src="https://github.com/ds4owd-001/project-efvicario/assets/106625395/0c934ce7-d7d8-41e8-9259-169a0dfe297a">
<img width="973" alt="Screenshot 2024-04-23 at 16 09 47" src="https://github.com/ds4owd-001/project-efvicario/assets/106625395/7063076b-5319-4b9c-9cf2-6307c9accea9">

Then, the correct link should be visible there. Let me know if this works!

We would love to work on the package then. Could you maybe start by uploading the rest of your data in the data-raw folder?

Thanks a lot!

**Comment by efvicario** [comment]
Hi!
I'm sorry, this has been on my list to do forever. I just added two new data files (in raw data folder) that I hope can be published, plus dictionaries (in the processed folder) for each. 
- household_survey and dictionary
- wp_survey and dictionary
I'm guessing they could use edits, please let me know what you think. 
Thanks,
Elizabeth

**Comment by efvicario** [comment]
Hi @margauxgo,
I just added a bit more information in the document about what kinds of variables are included in the dataset. Please let me know what else I can do to work towards publishing the dataset.
Thanks!
Elizabeth

**Comment by margauxgo** [comment]
Hi @efvicario,
Thank you for everything you've added! I started working on your data in the [watercostaccra repository](https://github.com/openwashdata/watercostaccra). As I am leaving the openwashdata team, @larnsce will take over from here. I hope we can publish your data soon!
